services:

  mysql:

    image: mysql:8.4

    container_name: recruitment-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recruitment_db

    ports:
      - "3307:3307"

  redis:

    image: redis:7

    container_name: redis

    ports:
      - "6379:6379"