spring:
  application:
    name: candidate-service

  datasource:
    url: jdbc:mysql://localhost:3306/hiring_platform?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      # Learning phase only
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

